# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('battles_total', models.IntegerField(verbose_name='Total battles')),
                ('wins_total', models.IntegerField(verbose_name='Total wins')),
                ('days_total', models.IntegerField(verbose_name='Totals days in game')),
                ('vehicles_x', models.IntegerField(verbose_name='Number of 10lvl vehicles')),
                ('exp_total', models.BigIntegerField(verbose_name='Total experience')),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
